server:
  servlet:
    context-path: '/'
  port: 1024
spring:
  profiles:
    active: 'dev'
# 项目配置
project:
  name: sa-admin
  module: net.lab1024.sa.admin.module
# swagger文档
swagger:
  host: localhost:${server.port}
  tag-class: net.lab1024.sa.admin.constant.AdminSwaggerTagConst
